---
- name: Include debain rust tasks
  ansible.builtin.include_tasks: debian.yml
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: Install rust
  community.general.homebrew:
    name: rust
    state: present
  when: ansible_distribution == 'MacOSX'
