- name: Download rustup installer script
  ansible.builtin.get_url:
    url: "https://sh.rustup.rs"
    dest: /tmp/rustup-init.sh
    mode: '0755'

- name: Install rustup
  ansible.builtin.shell: /tmp/rustup-init.sh -y
  args:
    creates: "{{ ansible_env.HOME }}/.cargo/bin/rustup"
    executable: /bin/bash

- name: Update Rust toolchain to stable
  ansible.builtin.shell: |
    source "{{ ansible_env.HOME }}/.cargo/env"
    rustup update stable
  args:
    executable: /bin/bash
  register: rustup_result
  changed_when: "'info: downloading' in rustup_result.stdout"
