---
- name: Include linux rust tasks
  ansible.builtin.include_tasks: linux.yml
  when: ansible_distribution in ['Debian', 'Ubuntu', 'Fedora']

- name: Install rust
  community.general.homebrew:
    name: rust
    state: present
  when: ansible_distribution == 'MacOSX'
