---
- name: Install development packages
  ansible.builtin.apt:
    name: "{{ devel_packages }}"
    state: present
  become: true

- name: Install development debian-based packages
  ansible.builtin.apt:
    name: "{{ devel_debian_packages }}"
    state: present
  become: true
