---
- name: Install development packages
  ansible.builtin.dnf:
    name: "{{ devel_packages }}"
    state: present
  become: true

- name: Install development Fedora-based packages
  ansible.builtin.dnf:
    name: "{{ devel_fedora_packages }}"
    state: present
  become: true

- name: Install development group packages
  ansible.builtin.dnf:
    name: "@Development Tools"
    state: present
  become: true
