wsl_conf_content: |
  [boot]
  systemd = true

  [network]
  generateResolvConf = true
  generateHosts = true

  [automount]
  enabled = true
  options = metadata,umask=22,fmask=11
  mountFsTab = true

  [interop]
  appendWindowsPath = false

wsl_conf_dest: /etc/wsl.conf
wsl_conf_mode: '0644'
