---
- name: Dotfiles playbook
  hosts: all
  pre_tasks:
    - name: Include pre_tasks
      ansible.builtin.include_tasks:
        file: pre_tasks.yml
  any_errors_fatal: true
  roles:
    - { role: base, when: effective_roles.base }
    - { role: zsh, when: effective_roles.zsh }
    - { role: git, when: effective_roles.git }
    - { role: llvm, when: effective_roles.llvm }
    - { role: rust, when: effective_roles.rust }
    - { role: go, when: effective_roles.go }
    - { role: neovim, when: effective_roles.neovim }
    - { role: tmux, when: effective_roles.tmux }
    - { role: zellij, when: effective_roles.zellij }
    - { role: devel, when: effective_roles.devel }
    - { role: gpg, when: effective_roles.gpg }
    - { role: fonts, when: effective_roles.fonts }
    - { role: gdb, when: effective_roles.gdb }
    - { role: wsl, when: effective_roles.wsl }
    - { role: proton, when: effective_roles.proton }
    - { role: desktop, when: effective_roles.desktop }
    - { role: alacritty, when: effective_roles.alacritty }
    - { role: ssh_profile, when: effective_roles.ssh_profile }
