- name: "Debian-based System Setup"
  hosts: all
  pre_tasks:
    - name: "Include pre_tasks"
      ansible.builtin.include_tasks:
        file: pre_tasks.yml
  any_errors_fatal: true
  vars_prompt:
    - name: git_user_name
      prompt: "Enter git config --global user.name"
      private: false
    - name: git_user_email
      prompt: "Enter git config --global user.email"
      private: false
  roles:
    - base
    - zsh
    - git
    - llvm
    - rust
    - go
    - neovim
    - tmux
    - gpg
    - fonts
    # - gdb
    - wsl
    - proton
    - desktop
    - alacritty
    - ssh_profile
