- name: "Debian System Setup"
  hosts: all
  pre_tasks:
    - name: Include and perform pre_tasks
      ansible.builtin.include_tasks:
        file: pre_tasks.yml
  any_errors_fatal: true
  vars_prompt:
    - name: git_user_name
      prompt: "Enter git config --global user.name"
      private: false
    - name: git_user_email
      prompt: "Enter git config --global user.email"
      private: false
  roles:
    - base
    - uv
    - zsh
    - git
    - llvm
    - rust
    - go
    - neovim
    - tmux
    - gpg
    - fonts
    - gdb
    - wsl
    - role: desktop
      tags: [desktop]
    - role: alacritty
      tags: [desktop]
    - role: ssh_profile
      tags: [dropbox]
