- name: "Check distro"
  ansible.builtin.assert:
    that:
      - ansible_distribution in ['Debian', 'Ubuntu']
    fail_msg: "This playbook is only for Debian-based systems"

- name: "Get system hostname"
  ansible.builtin.command: hostname
  register: system_hostname
  changed_when: true

- name: "Set hostname fact"
  ansible.builtin.set_fact:
    ansible_hostname: "{{ system_hostname.stdout }}"

- name: "Check if host_vars/<hostname>.yml file exists"
  ansible.builtin.stat:
    path: "host_vars/{{ ansible_hostname }}.yml"
  register: host_vars_file

- name: "Prompt for continuation if file doesn't exist"
  ansible.builtin.pause:
    prompt: "host_vars/{{ ansible_hostname }}.yml doesn't exist. Press ENTER to continue or Ctrl+C to abort"
  when: not host_vars_file.stat.exists

- name: "Load host-specific variables if available"
  ansible.builtin.include_vars: "host_vars/{{ ansible_hostname }}.yml"
  when: host_vars_file.stat.exists

- name: "Update collection community.general to latest"
  community.general.ansible_galaxy_install:
    type: collection
    name: community.general
    state: latest

- name: "Add NOPASSWD Entry for User"
  community.general.sudoers:
    name: "NOPASSWD-for-{{ ansible_user_id }}"
    user: "{{ ansible_user_id }}"
    commands: ALL
    nopassword: true
    state: present
  become: true

- name: "Include additional fact gathering tasks"
  ansible.builtin.import_tasks:
    file: fact_gatherer.yml
