live_config_reload = true
import = [
'~/.config/alacritty/colors.toml',
'~/.config/alacritty/font.toml',
'~/.config/alacritty/mouse.toml',
'~/.config/alacritty/window.toml',
'~/.config/alacritty/local.toml',
]
