# Active Color Scheme: One Dark
#[colors.primary]
#  background = '#282c34'
#  foreground = '#abb2bf'

# Cursor Colors
[colors.cursor]
text = 'CellBackground'  # Note: 'CellBackground' and 'CellForeground' are placeholders. Replace with actual color codes if necessary.
cursor = '#528bff'

# Selection Colors
[colors.selection]
text = 'CellForeground'
background = '#3e4451'

# Normal Colors
#[colors.normal]
#  black = '#5c6370'
#  red = '#e06c75'
#  green = '#98c379'
#  yellow = '#e5c07b'
#  blue = '#61afef'
#  magenta = '#c678dd'
#  cyan = '#56b6c2'
#  white = '#828997'
