---
- name: Ensure Zed config directory exists
  file:
    path: "{{ ansible_user_dir }}/.config/zed"
    state: directory
    mode: "0755"

- name: Clone Zed repository
  git:
    repo: "{{ zed_repo_url }}"
    dest: "{{ zed_clone_dest }}"
    version: "{{ zed_repo_version }}"
    update: yes

- name: Copy Zed binary to local bin
  copy:
    src: "{{ zed_clone_dest }}/zed"
    dest: "{{ ansible_user_dir }}/.local/bin/zed"
    mode: "0755"
    remote_src: yes

- name: Symlink keybindings.json
  file:
    src: "{{ role_path }}/files/keybindings.json"
    dest: "{{ ansible_user_dir }}/.config/zed/keybindings.json"
    state: link
    force: yes

- name: Symlink settings.json
  file:
    src: "{{ role_path }}/files/settings.json"
    dest: "{{ ansible_user_dir }}/.config/zed/settings.json"
    state: link
    force: yes
