default_roles:
  base: true
  zsh: true
  git: true
  go: false
  fonts: false
  neovim: false
  tmux: true
  zellij: true
  devel: false
  llvm: false
  rust: true
  gpg: false
  gdb: false
  wsl: false
  proton: false
  desktop: false
  alacritty: false
  ssh_profile: false
