name: 'Setup and Run Dotfiles for macOS'
description: 'Sets up environment and runs the dotfiles setup script on macOS'
inputs:
  setup_args:
    description: 'Arguments to pass to setup.sh'
    required: false
    default: ''
  sh_args:
    description: 'Shell arguments for setup.sh'
    required: false
    default: ''
  task_name:
    description: 'Name of the task being executed'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Set environment variables
      shell: bash
      run: |
        echo "DOTFILES_LOCATION=$GITHUB_WORKSPACE" >> "$GITHUB_ENV"

    - name: Set commit variable
      shell: bash
      run: |
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          echo "COMMIT=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
        else
          echo "COMMIT=${{ github.sha }}" >> $GITHUB_ENV
        fi

    - name: "Exec task (${{ inputs.task_name }}): $ setup.sh ${{ inputs.setup_args }}"
      shell: bash
      env:
        SETUP_ARGS: ${{ inputs.setup_args }}
        SH_ARGS: ${{ inputs.sh_args }}
      run: |
        curl -LsS https://raw.githubusercontent.com/tkk2112/dotfiles/${COMMIT}/setup.sh | sh ${SH_ARGS}-s -- ${SETUP_ARGS}
