---
- name: Install LLVM and Clang components
  ansible.builtin.dnf:
    name:
      - llvm
      - clang
      - clang-tools-extra
      - lld
      - lldb
    state: present
  become: true

- name: Install libc++ and libc++abi for default LLVM version
  ansible.builtin.dnf:
    name:
      - libcxx
      - libcxx-devel
      - libcxxabi
    state: present
  become: true
