- name: Fetch LLVM GPG key
  ansible.builtin.get_url:
    url: "{{ llvm_apt_repo_base }}/llvm-snapshot.gpg.key"
    dest: /etc/apt/keyrings/apt.llvm.org.asc
    mode: "0644"
  become: true

- name: Configure LLVM base apt repository
  ansible.builtin.deb822_repository:
    name: llvm
    types: deb
    uris: "{{ llvm_apt_repo_base }}/{{ llvm_apt_codename }}/"
    suites: "{{ 'llvm-toolchain' if base_debian_enable_testing else 'llvm-toolchain-' + ansible_distribution_release }}"
    components:
      - "{{ llvm_apt_component }}"
    signed_by: /etc/apt/keyrings/apt.llvm.org.asc
    state: present
  become: true

- name: Add LLVM version-specific repositories
  ansible.builtin.deb822_repository:
    name: "llvm-{{ item }}"
    types: deb
    uris: "{{ llvm_apt_repo_base }}/{{ llvm_apt_codename }}/"
    suites: "{{ 'llvm-toolchain' if base_debian_enable_testing else 'llvm-toolchain-' + ansible_distribution_release }}-{{ item }}"
    components:
      - "{{ llvm_apt_component }}"
    signed_by: /etc/apt/keyrings/apt.llvm.org.asc
    state: present
  loop: "{{ llvm_versions }}"
  become: true

- name: Update APT cache and perform dist upgrade
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
  become: true

- name: Install LLVM and Clang components
  ansible.builtin.apt:
    name:
      - "llvm-{{ item }}"
      - "clang-{{ item }}"
      - "clang-tools-{{ item }}"
      - "clangd-{{ item }}"
      - "clang-format-{{ item }}"
      - "lld-{{ item }}"
      - "lldb-{{ item }}"
    state: present
    allow_change_held_packages: true
  loop: "{{ llvm_versions }}"
  become: true

- name: Install libc++ and libc++abi for default LLVM version
  ansible.builtin.apt:
    name:
      - "libc++-{{ llvm_default_version }}-dev"
      - "libc++abi-{{ llvm_default_version }}-dev"
    state: present
  when: llvm_versions | length > 0
  become: true
