- name: Fetch LLVM GPG key
  ansible.builtin.get_url:
    url: "{{ llvm_apt_repo_base }}/llvm-snapshot.gpg.key"
    dest: /etc/apt/keyrings/apt.llvm.org.asc
    mode: "0644"
  become: true

- name: Configure LLVM base apt repository
  ansible.builtin.apt_repository:
    # yamllint disable-line rule:line-length
    repo: "deb [signed-by=/etc/apt/keyrings/apt.llvm.org.asc] {{ llvm_apt_repo_base }}/{{ llvm_apt_codename }}/ {{ 'llvm-toolchain' if base_enable_testing else 'llvm-toolchain-' + ansible_distribution_release }} {{ llvm_apt_component }}"
    state: present
    filename: llvm
  become: true

- name: Add LLVM version-specific repositories
  ansible.builtin.apt_repository:
    # yamllint disable-line rule:line-length
    repo: "deb [signed-by=/etc/apt/keyrings/apt.llvm.org.asc] {{ llvm_apt_repo_base }}/{{ llvm_apt_codename }}/ {{ 'llvm-toolchain' if base_enable_testing else 'llvm-toolchain-' + ansible_distribution_release }}-{{ item }} {{ llvm_apt_component }}"
    state: present
    filename: "llvm-{{ item }}"
  loop: "{{ llvm_versions }}"
  become: true

- name: Update APT cache and perform dist upgrade
  ansible.builtin.apt:
    update_cache: true
    upgrade: dist
  become: true

- name: Install LLVM and Clang components
  ansible.builtin.apt:
    name:
      - "llvm-{{ item }}"
      - "clang-{{ item }}"
      - "clang-tools-{{ item }}"
      - "clangd-{{ item }}"
      - "clang-format-{{ item }}"
      - "lld-{{ item }}"
      - "lldb-{{ item }}"
    state: present
    allow_change_held_packages: true
  loop: "{{ llvm_versions }}"
  become: true

- name: Install libc++ and libc++abi for default LLVM version
  ansible.builtin.apt:
    name:
      - "libc++-{{ llvm_default_version }}-dev"
      - "libc++abi-{{ llvm_default_version }}-dev"
    state: present
  when: llvm_versions | length > 0
  become: true
