---
- name: Include LLVM installation tasks
  ansible.builtin.include_tasks:
    file: debian_based.yml
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: Include LLVM alternatives registration tasks
  ansible.builtin.import_tasks:
    file: register_alternatives.yml
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: Include LLVM installation tasks
  ansible.builtin.include_tasks:
    file: fedora.yml
  when: ansible_distribution == 'Fedora'
