- name: Register LLVM alternatives for version {{ item }}
  ansible.builtin.shell: |
    update-alternatives \
        --install /usr/bin/clang                 clang                 /usr/bin/clang-{{ item }} 100 \
        --slave   /usr/bin/clang++               clang++               /usr/bin/clang++-{{ item }}  \
        --slave   /usr/bin/clangd                clangd                /usr/bin/clangd-{{ item }}  \
        --slave   /usr/bin/asan_symbolize        asan_symbolize        /usr/bin/asan_symbolize-{{ item }} \
        --slave   /usr/bin/c-index-test          c-index-test          /usr/bin/c-index-test-{{ item }} \
        --slave   /usr/bin/clang-check           clang-check           /usr/bin/clang-check-{{ item }} \
        --slave   /usr/bin/clang-cl              clang-cl              /usr/bin/clang-cl-{{ item }} \
        --slave   /usr/bin/clang-cpp             clang-cpp             /usr/bin/clang-cpp-{{ item }} \
        --slave   /usr/bin/clang-format          clang-format          /usr/bin/clang-format-{{ item }} \
        --slave   /usr/bin/clang-format-diff     clang-format-diff     /usr/bin/clang-format-diff-{{ item }} \
        --slave   /usr/bin/clang-include-fixer   clang-include-fixer   /usr/bin/clang-include-fixer-{{ item }} \
        --slave   /usr/bin/clang-offload-bundler clang-offload-bundler /usr/bin/clang-offload-bundler-{{ item }} \
        --slave   /usr/bin/clang-query           clang-query           /usr/bin/clang-query-{{ item }} \
        --slave   /usr/bin/clang-rename          clang-rename          /usr/bin/clang-rename-{{ item }} \
        --slave   /usr/bin/clang-reorder-fields  clang-reorder-fields  /usr/bin/clang-reorder-fields-{{ item }} \
        --slave   /usr/bin/clang-tidy            clang-tidy            /usr/bin/clang-tidy-{{ item }} \
        \
        --slave   /usr/bin/lld                   lld                   /usr/bin/lld-{{ item }} \
        --slave   /usr/bin/ld.lld                ld.lld                /usr/bin/ld.lld-{{ item }} \
        --slave   /usr/bin/lldb                  lldb                  /usr/bin/lldb-{{ item }} \
        --slave   /usr/bin/lldb-server           lldb-server           /usr/bin/lldb-server-{{ item }} \
        --slave   /usr/bin/llvm-config           llvm-config           /usr/bin/llvm-config-{{ item }} \
        --slave   /usr/bin/llvm-ar               llvm-ar               /usr/bin/llvm-ar-{{ item }} \
        --slave   /usr/bin/llvm-as               llvm-as               /usr/bin/llvm-as-{{ item }} \
        --slave   /usr/bin/llvm-bcanalyzer       llvm-bcanalyzer       /usr/bin/llvm-bcanalyzer-{{ item }} \
        --slave   /usr/bin/llvm-cov              llvm-cov              /usr/bin/llvm-cov-{{ item }} \
        --slave   /usr/bin/llvm-diff             llvm-diff             /usr/bin/llvm-diff-{{ item }} \
        --slave   /usr/bin/llvm-dis              llvm-dis              /usr/bin/llvm-dis-{{ item }} \
        --slave   /usr/bin/llvm-dwarfdump        llvm-dwarfdump        /usr/bin/llvm-dwarfdump-{{ item }} \
        --slave   /usr/bin/llvm-extract          llvm-extract          /usr/bin/llvm-extract-{{ item }} \
        --slave   /usr/bin/llvm-link             llvm-link             /usr/bin/llvm-link-{{ item }} \
        --slave   /usr/bin/llvm-mc               llvm-mc               /usr/bin/llvm-mc-{{ item }} \
        --slave   /usr/bin/llvm-nm               llvm-nm               /usr/bin/llvm-nm-{{ item }} \
        --slave   /usr/bin/llvm-objdump          llvm-objdump          /usr/bin/llvm-objdump-{{ item }} \
        --slave   /usr/bin/llvm-ranlib           llvm-ranlib           /usr/bin/llvm-ranlib-{{ item }} \
        --slave   /usr/bin/llvm-readobj          llvm-readobj          /usr/bin/llvm-readobj-{{ item }} \
        --slave   /usr/bin/llvm-rtdyld           llvm-rtdyld           /usr/bin/llvm-rtdyld-{{ item }} \
        --slave   /usr/bin/llvm-size             llvm-size             /usr/bin/llvm-size-{{ item }} \
        --slave   /usr/bin/llvm-stress           llvm-stress           /usr/bin/llvm-stress-{{ item }} \
        --slave   /usr/bin/llvm-symbolizer       llvm-symbolizer       /usr/bin/llvm-symbolizer-{{ item }} \
        --slave   /usr/bin/llvm-tblgen           llvm-tblgen           /usr/bin/llvm-tblgen-{{ item }}
  loop: "{{ llvm_versions }}"
  changed_when: false
  become: true
