- name: Install rclone
  ansible.builtin.command:
    cmd: go install github.com/rclone/rclone@latest
  environment:
    GOPATH: "{{ gopath }}"
  args:
    creates: "{{ gopath }}/bin/rclone"

- name: Ensure rclone config directory exists
  ansible.builtin.file:
    path: "~/.config/rclone"
    state: directory
    mode: "0700"

- name: Check if rclone config exists
  ansible.builtin.stat:
    path: "~/.config/rclone/rclone.conf"
  register: rclone_config

- name: Check for client_access_token in config
  ansible.builtin.command:
    cmd: grep -q "client_access_token" ~/.config/rclone/rclone.conf
  register: token_check
  failed_when: false
  changed_when: false
  when: rclone_config.stat.exists

- name: Configure rclone for ProtonDrive
  ansible.builtin.copy:
    dest: "~/.config/rclone/rclone.conf"
    content: |
      [protondrive]
      type = protondrive
    mode: "0600"
  when: not rclone_config.stat.exists or (token_check.rc != 0)

- name: "Ask for Proton username"
  ansible.builtin.pause:
    prompt: "Enter Proton username: "
    echo: true
  register: proton_username
  no_log: true
  when: not rclone_config.stat.exists or (token_check.rc != 0)

- name: "Ask for Proton password"
  ansible.builtin.pause:
    prompt: "Enter Proton password: "
    echo: false
  register: proton_password
  no_log: true
  when: not rclone_config.stat.exists or (token_check.rc != 0)

- name: "Ask for Proton 2FA"
  ansible.builtin.pause:
    prompt: "Enter Proton 2FA: "
    echo: true
  register: proton_2fa
  no_log: true
  when: not rclone_config.stat.exists or (token_check.rc != 0)

- name: Obscure the password using rclone
  ansible.builtin.command:
    cmd: rclone obscure {{ proton_password.user_input }}
  register: obscured_password
  no_log: true
  when: not rclone_config.stat.exists or (token_check.rc != 0)
  changed_when: false

- name: Login to ProtonDrive to store client_access_token
  ansible.builtin.command:
    # yamllint disable-line rule:line-length
    cmd: "rclone about protondrive: --protondrive-username {{ proton_username.user_input }} --protondrive-password {{ obscured_password.stdout }} --protondrive-2fa={{ proton_2fa.user_input }}"
  no_log: true
  when: not rclone_config.stat.exists or (token_check.rc != 0)
  changed_when: false

- name: Ensure rclone config has correct permissions
  ansible.builtin.file:
    path: "~/.config/rclone/rclone.conf"
    mode: "0600"

- name: Create ProtonDrive directory
  ansible.builtin.file:
    path: "~/ProtonDrive"
    state: directory
    mode: "0700"

- name: Create systemd service for ProtonDrive mount
  ansible.builtin.copy:
    dest: "~/.config/systemd/user/protondrive.service"
    content: |
      [Unit]
      Description=Rclone mount service
      After=network.target
      Wants=network-online.target
      StartLimitIntervalSec=300
      StartLimitBurst=3

      [Service]
      Type=simple
      Environment="RCLONE_LOG_LEVEL=INFO"
      Environment="RCLONE_USER_SOURCE_NAME=protondrive"
      Environment="RCLONE_USER_SOURCE_DIRECTORY="
      Environment="RCLONE_USER_TARGET_DIRECTORY=%h/ProtonDrive"
      Environment="RCLONE_VFS_CACHE_MODE=full"
      ExecStartPre=/usr/bin/mkdir -p ${RCLONE_USER_TARGET_DIRECTORY}
      ExecStart={{ gopath }}/bin/rclone --log-level=${RCLONE_LOG_LEVEL} --vfs-cache-mode ${RCLONE_VFS_CACHE_MODE} mount ${RCLONE_USER_SOURCE_NAME}:${RCLONE_USER_SOURCE_DIRECTORY} ${RCLONE_USER_TARGET_DIRECTORY}
      ExecStop=/usr/bin/fusermount -uz ${RCLONE_USER_TARGET_DIRECTORY}
      Restart=on-failure
      RestartSec=5
      StandardOutput=journal
      StandardError=journal

      [Install]
      WantedBy=default.target
    mode: "0644"

- name: Enable and start ProtonDrive service
  ansible.builtin.systemd:
    name: protondrive
    enabled: true
    state: started
    scope: user
    daemon_reload: true
