- name: Create /etc/wsl.conf with WSL configuration
  ansible.builtin.copy:
    dest: "{{ wsl_conf_dest }}"
    content: "{{ wsl_conf_content }}"
    mode: "{{ wsl_conf_mode }}"
  become: true
  when: ansible_virtualization_type == 'wsl'

- name: Add DNS to resolved.conf
  ansible.builtin.blockinfile:
    path: "/etc/systemd/resolved.conf"
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR resolved.conf"
    block: |
      DNS=10.0.10.101 10.0.0.11
  become: true
  when:
    - ansible_virtualization_type == 'wsl'
    - internal is defined
    - internal | bool
