---
- name: Create /etc/wsl.conf with WSL configuration
  ansible.builtin.copy:
    dest: /etc/wsl.conf
    content: "{{ wsl_conf_content }}"
    mode: "0644"
  become: true

- name: Create custom resolv.conf with DNS settings
  ansible.builtin.template:
    src: "{{ role_path }}/files/resolv.conf.j2"
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: "0644"
  become: true
  when: internal | bool

- name: Create initial env file with PATH case structure
  ansible.builtin.copy:
    dest: /etc/hosts
    content: |
      127.0.0.1       localhost
      127.0.0.1       wsl.local wsl
      ::1             localhost ip6-localhost ip6-loopback
      ff02::1         ip6-allnodes
      ff02::2         ip6-allrouters
    mode: "0644"
  become: true

- name: Set DISPLAY environment variable
  ansible.builtin.blockinfile:
    path: /etc/zsh/zprofile
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR DISPLAY"
    block: |
      {% if current_site == 'SWE' %}
      export DISPLAY=10.0.10.2:0.0
      {% elif current_site == 'NOR' %}
      export DISPLAY=10.0.0.2:0.0
      {% endif %}
  become: true
  when:
    - current_site in ['SWE', 'NOR']
    - internal | bool
