FROM fedora:42
ENV container=docker

RUN dnf -y upgrade \
    && dnf -y install \
      sudo \
      shadow-utils \
      passwd \
    && dnf -y group install \
        admin-tools \
        cosmic-desktop \
        cosmic-desktop-apps \
        desktop-accessibility \
    && dnf clean all

RUN getent group shadow || groupadd -r shadow

RUN chown root:shadow /etc/shadow \
    && chmod 640 /etc/shadow

RUN useradd --uid 1000 \
      --shell /usr/bin/bash \
      --groups wheel \
      --create-home \
      fedora \
    && echo 'fedora ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers \
    && echo 'Defaults:fedora !requiretty' >> /etc/sudoers


VOLUME [ "/sys/fs/cgroup" ]
CMD ["/usr/lib/systemd/systemd"]
