- name: Ensure systemd user directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/systemd/user"
    state: directory
    mode: "0700"

- name: Enable service systemd-resolved
  ansible.builtin.systemd_service:
    name: systemd-resolved
    enabled: true

- name: Enable service ssh
  ansible.builtin.systemd_service:
    name: ssh
    enabled: true
