- name: Create tldr share directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/share/tldr"
    state: directory
    mode: "0755"

- name: Update tldr pages
  ansible.builtin.command: tldr -u
  run_once: true
  changed_when: true

- name: Add tldr update to crontab
  ansible.builtin.cron:
    name: "update tldr pages"
    minute: "0"
    hour: "0"
    day: "*"
    month: "*"
    weekday: "0"
    job: "/usr/bin/tldr -u > /dev/null"

- name: Symlink .direnvrc configuration
  ansible.builtin.file:
    src: "{{ role_path }}/files/.direnvrc"
    dest: "{{ ansible_env.HOME }}/.direnvrc"
    state: link
    force: true
