---
- name: Install GPG tools and utilities (debian)
  ansible.builtin.package:
    name:
      - gnupg
      - pinentry-curses
      - pcscd
      - scdaemon
      - yubikey-manager
    state: present
  become: true
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: Install GPG tools and utilities (fedora)
  ansible.builtin.package:
    name:
      - pinentry-tty
      - pcsc-tools
      - opensc
      - pcsc-lite
      - yubikey-manager
    state: present
  become: true
  when: ansible_distribution == 'Fedora'
