- name: Set architecture specific variables
  ansible.builtin.set_fact:
    pwndbg_arch: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"

- name: Install radare2 and pip
  ansible.builtin.apt:
    name:
      - radare2
      - python3-pip
    state: present
  become: true

- name: Download pwndbg package
  ansible.builtin.get_url:
    url: "https://github.com/pwndbg/pwndbg/releases/download/{{ gdb_pwndbg_version }}/pwndbg_{{ gdb_pwndbg_version }}_{{ pwndbg_arch }}.deb"
    dest: "/tmp/pwndbg.deb"
    mode: '0644'

- name: Install pwndbg package
  ansible.builtin.apt:
    deb: "/tmp/pwndbg.deb"
    state: present
  become: true

- name: Get PWNDBG Python version
  ansible.builtin.shell: "set -o pipefail && dpkg -L pwndbg | grep -o 'python3\\.[0-9]\\+' | sort -u | head -n1"
  register: pwndbg_python_version
  changed_when: false

- name: Install Python packages for pwndbg
  ansible.builtin.command:
    cmd: /usr/bin/python3 -m pip install --target=/usr/lib/pwndbg/lib/{{ pwndbg_python_version.stdout }}/site-packages r2pipe colorama prompt-toolkit pygments
  become: true
  changed_when: false
  args:
    creates:
      - /usr/lib/pwndbg/lib/{{ pwndbg_python_version.stdout }}/site-packages/r2pipe
      - /usr/lib/pwndbg/lib/{{ pwndbg_python_version.stdout }}/site-packages/colorama
      - /usr/lib/pwndbg/lib/{{ pwndbg_python_version.stdout }}/site-packages/prompt_toolkit
      - /usr/lib/pwndbg/lib/{{ pwndbg_python_version.stdout }}/site-packages/pygments

- name: Update r2pm database
  ansible.builtin.command: r2pm -U -f
  changed_when: false

- name: Install r2pm packages
  ansible.builtin.shell: |
    set -o pipefail
    if ! r2pm -l | grep -q "^{{ item }}$"; then
      r2pm -ci {{ item }}
    fi
  loop: "{{ gdb_r2pm_packages }}"
  changed_when: false

- name: Update all r2pm packages
  ansible.builtin.command: r2pm -UU -f
  changed_when: false

- name: Install pwndbg as gdb
  community.general.alternatives:
    name: gdb
    path: /usr/bin/pwndbg
    link: /usr/local/bin/gdb
    state: present
  become: true
