name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Install Python"
        uses: actions/setup-python@v4
        with:
            python-version: "3.12"

      - name: "Cache python packages"
        uses: actions/cache@v4
        with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-latest

      - name: "Install packages"
        shell: bash
        run: |
            python -m pip install ansible ansible-lint yamllint

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set branch name
        id: set_branch
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "BRANCH=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
          else
            echo "BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
          fi

      - name: Run linter
        run: |
          curl -LsSf "https://raw.githubusercontent.com/tkk2112/dotfiles/refs/heads/${BRANCH}/setup.sh" | sh -x -s -- --lint-only

      - name: Run playbook
        run: |
          curl -LsSf "https://raw.githubusercontent.com/tkk2112/dotfiles/refs/heads/${BRANCH}/setup.sh" | sh -x -s -- --skip-lint -v
