---
name: .dotfiles PR

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  pull_request:

jobs:
  check:
    name: pre-commit
    runs-on: ubuntu-latest
    env:
      DOTFILES_CI: 'true'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: astral-sh/setup-uv@eac588ad8def6316056a12d4907a9d4d84ff7a3b # v7.3.0
        with:
          enable-cache: true

      - uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-5|${{ runner.os }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Run pre-commit
        run: uv tool run pre-commit run --all-files

  install-linux:
    needs: check
    name: install on ${{ matrix.image }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - ubuntu:24.04
          - ubuntu:latest
          - debian:13
          - debian:sid
          - fedora:42
          - fedora:latest
          - alpine:latest
          - archlinux:latest

    container:
      image: ${{ matrix.image }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run dotfiles install test
        env:
          DOTFILES_CI: 'true'
          DOTFILES_LOCATION: ${{ github.workspace }}
        run: ./scripts/ci-install.sh

  install-macos:
    needs: check
    name: install on macos:latest
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Run dotfiles install test
        env:
          DOTFILES_CI: 'true'
          DOTFILES_LOCATION: ${{ github.workspace }}
        run: ./scripts/ci-install.sh
