name: Standard

on:
  push:
    branches: [main]

jobs:
  check:
    if: github.ref == 'refs/heads/main'
    name: check'n'test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: astral-sh/setup-uv@b75a909f75acd358c2196fb9a5f1299a9a8868a4 # v6.7.0
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-5|${{ hashFiles('uv.lock') }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - run: uv run alias check
      - run: uv run alias test

  standard-run:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Verify url shortener is pointing to latest setup.sh
        run: |
          GITHUB_URL="https://raw.githubusercontent.com/tkk2112/dotfiles/refs/heads/main/setup.sh"
          CUSTOM_URL="https://link.m04r.space/dotfiles"

          # Get content from both URLs
          GITHUB_CONTENT=$(curl -Ls "$GITHUB_URL")
          GITHUB_CHECKSUM=$(curl -Ls "$GITHUB_URL" | sha256sum | cut -d' ' -f1)
          CUSTOM_CHECKSUM=$(curl -Ls "$CUSTOM_URL" | sha256sum | cut -d' ' -f1)

          echo "Comparing checksums:"
          echo "GitHub ($GITHUB_URL): $GITHUB_CHECKSUM"
          echo "Custom ($CUSTOM_URL): $CUSTOM_CHECKSUM"

          if [ "$GITHUB_CHECKSUM" != "$CUSTOM_CHECKSUM" ]; then
            echo "Error: Custom URL content checksum differs from GitHub URL content checksum"
            exit 1
          fi

      - name: Prepare container for setup script
        run: |
          cat > "script-$GITHUB_RUN_ID.sh" << 'EOF'
          #!/bin/sh
          DEBIAN_FRONTEND=noninteractive apt -qq update </dev/null >/dev/null
          DEBIAN_FRONTEND=noninteractive apt -qq install -y apt-utils curl sudo curl </dev/null >/dev/null
          useradd -m -s /bin/bash newuser
          echo 'newuser ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers
          su --login newuser -c 'curl -LsS https://link.m04r.space/dotfiles | sh'
          EOF

      - name: Run setup script as advertised in README.md
        uses: docker://debian:latest
        with:
          entrypoint: /bin/sh
          args: script-${{ github.run_id }}.sh
