---
- name: Install latest version of zellij
  community.general.cargo:
    name: zellij
    state: latest
  environment:
    PATH: "{{ ansible_env.HOME }}/.cargo/bin:{{ ansible_env.PATH }}"

- name: Create zellij config directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/zellij"
    state: directory
    mode: "0755"

- name: Symlink configuration file
  ansible.builtin.file:
    src: "{{ role_path }}/files/config.kdl"
    dest: "{{ ansible_env.HOME }}/.config/zellij/config.kdl"
    state: link
    force: true
