- name: Create fonts directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/share/fonts"
    state: directory
    mode: "0755"

- name: Install FiraCode Nerd Font
  ansible.builtin.import_tasks:
    file: firacode_nerd_font.yml

- name: Refresh system font cache
  ansible.builtin.command: fc-cache -fv
  changed_when: true
